# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-16 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrocognitive_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_data',
            field=models.CharField(blank=True, max_length=2000000, null=True),
        ),
    ]
